/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import DAO.FlorDAO;
import JavaBeans.Flor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas
 */
public class Flor_Tela extends javax.swing.JFrame {
    
    public int cod;
    
    //Metodo Listar
     public void Listar(){
        try {
            //1º Executar o Select
            FlorDAO dao = new FlorDAO();
            
            List<Flor> listaFlo = dao.ListarFlores();
            
            //2ºColocar os dados na tabela
            
            DefaultTableModel modelo = (DefaultTableModel)Tabela_Flor.getModel();
            modelo.setNumRows(0);
            
            for(Flor f : listaFlo){
                modelo.addRow(new Object[]{
                    f.getCod_flor(),
                    f.getNome(),
                    f.getQtd_flor(),
                    
                    });
            }
            
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    
    
    /**
     * Creates new form Flor_Tela
     */
    public Flor_Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Cadastro = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Nome_flor = new javax.swing.JTextField();
        txt_qtd_flor = new javax.swing.JTextField();
        btn_cadastrar_Flor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        Painel_Editar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Flor = new javax.swing.JTable();
        btn_Excluir = new javax.swing.JButton();
        btn_Editar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Flores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Painel_Cadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cadastrar Flores");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Quantidade");

        btn_cadastrar_Flor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cadastrar_Flor.setText("Cadastrar");
        btn_cadastrar_Flor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrar_FlorActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar dados");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Painel_CadastroLayout = new javax.swing.GroupLayout(Painel_Cadastro);
        Painel_Cadastro.setLayout(Painel_CadastroLayout);
        Painel_CadastroLayout.setHorizontalGroup(
            Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_CadastroLayout.createSequentialGroup()
                .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_CadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Painel_CadastroLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                .addComponent(btn_cadastrar_Flor))
                            .addComponent(txt_qtd_flor)
                            .addComponent(txt_Nome_flor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_CadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_limpar))
                    .addGroup(Painel_CadastroLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        Painel_CadastroLayout.setVerticalGroup(
            Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_CadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(btn_limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Nome_flor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_qtd_flor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Painel_CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrar_Flor)
                    .addComponent(jButton2))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flores");

        menu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menu.setText("Menu");
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });

        Painel_Editar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabela_Flor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Tabela_Flor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_Flor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabela_Flor.getTableHeader().setReorderingAllowed(false);
        Tabela_Flor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_FlorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Flor);
        if (Tabela_Flor.getColumnModel().getColumnCount() > 0) {
            Tabela_Flor.getColumnModel().getColumn(0).setMinWidth(50);
            Tabela_Flor.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        btn_Excluir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        btn_Editar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_Editar.setText("Editar");
        btn_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Listagem de Flores");

        javax.swing.GroupLayout Painel_EditarLayout = new javax.swing.GroupLayout(Painel_Editar);
        Painel_Editar.setLayout(Painel_EditarLayout);
        Painel_EditarLayout.setHorizontalGroup(
            Painel_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Painel_EditarLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btn_Editar)
                .addGap(109, 109, 109))
            .addGroup(Painel_EditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Painel_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Painel_EditarLayout.setVerticalGroup(
            Painel_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_EditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Painel_EditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Editar))
                .addGap(92, 92, 92))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Painel_Cadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Painel_Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Painel_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Painel_Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrar_FlorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrar_FlorActionPerformed

        //Botão Cadastrar Produto

        //Verifica se algum campo esta vazio !
        if(!txt_Nome_flor.getText().isEmpty() && !txt_qtd_flor.getText().isEmpty()){
            try {
                //1º Guardar os dados do formulario em um obj Produto

                Flor flor = new Flor();
                flor.setNome(txt_Nome_flor.getText());
                flor.setQtd_flor(Integer.parseInt(txt_qtd_flor.getText()));

                //2º passo Criar um flor do tipo DAO
                FlorDAO dao = new FlorDAO();
                dao.cadastrarFlor(flor);

                JOptionPane.showMessageDialog(null,"Cadastro Realizado Com Sucesso");

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null,"Erro Ao Cadastrar ! " +erro);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Os Campos não podem estar vazios Tente de novo ! ");
        }
    }//GEN-LAST:event_btn_cadastrar_FlorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        // Limpar todos os campos
        txt_Nome_flor.setText(null);
        txt_qtd_flor.setText(null);
       
        
    }//GEN-LAST:event_btn_limparActionPerformed

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        Menu e = new Menu();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuMouseClicked

    private void Tabela_FlorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_FlorMouseClicked
        // Pegando dados
        cod = Integer.parseInt(Tabela_Flor.getValueAt(Tabela_Flor.getSelectedRow(), 0).toString());

        txt_Nome_flor.setText(Tabela_Flor.getValueAt(Tabela_Flor.getSelectedRow(), 1).toString());
        txt_qtd_flor.setText(Tabela_Flor.getValueAt(Tabela_Flor.getSelectedRow(), 2).toString());
        
    }//GEN-LAST:event_Tabela_FlorMouseClicked

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        // Botão Excluir:

        if(!txt_Nome_flor.getText().isEmpty()){
            int resposta = JOptionPane.showConfirmDialog(null,"Você realmente quer excluir esta Flor ?");
            if(resposta == JOptionPane.YES_OPTION){
                try {
                    //1º Guardar os dados do formulario em um obj Produto

                    Flor flor= new Flor();
                    flor.setCod_flor(cod);

                    //2º passo Criar um prod do tipo DAO
                   FlorDAO dao = new FlorDAO();
                    dao.excluirFlor(flor);

                    JOptionPane.showMessageDialog(null,"Excluido Com Sucesso");

                } catch (Exception erro) {
                    JOptionPane.showMessageDialog(null,"Erro Ao Excluir ! " +erro);
                }
            }
        }
        else
        JOptionPane.showMessageDialog(null,"Selecione uma Flor antes ! ");
    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void btn_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditarActionPerformed
        // Botão Editar:

        //Verifica se algum campo esta vazio !
        if(!txt_Nome_flor.getText().isEmpty()){
            try {
                //1º Guardar os dados do formulario em um obj Produto

                Flor f = new Flor();
                f.setCod_flor(cod);
                f.setNome(txt_Nome_flor.getText());
                f.setQtd_flor(Integer.parseInt(txt_qtd_flor.getText()));
                

                //2º passo Criar um prod do tipo DAO
                FlorDAO dao = new FlorDAO();
                dao.editarFlor(f);

                JOptionPane.showMessageDialog(null,"Alterado Com Sucesso");

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null,"Erro Ao Alterar ! " +erro);
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Selecione um Cliente antes ! ");
        }
    }//GEN-LAST:event_btn_EditarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Listar();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flor_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flor_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flor_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flor_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flor_Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Cadastro;
    private javax.swing.JPanel Painel_Editar;
    private javax.swing.JTable Tabela_Flor;
    private javax.swing.JButton btn_Editar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_cadastrar_Flor;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel menu;
    private javax.swing.JTextField txt_Nome_flor;
    private javax.swing.JTextField txt_qtd_flor;
    // End of variables declaration//GEN-END:variables
}
